### ISSUE TITLE
STL File Parameterization Error

### ISSUE THREAD

**Issue by LauraVargas9** [Philipp-MR/CoilGen#6]
Dear Dr. Amrein,

I am experiencing some issues with a PTC CREO STL file I created. The geometry is a hollow half-sphere similar to the "half_sphere_shape" STL included in the Geometry_Data directory, but without the side rims. The MATLAB error I'm getting is the following:

Index in position 2 exceeds
array bounds.

Error in parameterize_mesh (line 33)
    is_new_node=[boundary_edges(:,1)' 0]==[0 boundary_edges(:,2)'];

Error in CoilGen (line 59)
coil_parts=parameterize_mesh(coil_parts,input);

Error in test (line 20)
    coil_layouts(coil_ind).out=CoilGen(...
 
Could you please advise me on how to resolve this issue?
Thank you so much.

**Comment by Philipp-MR** [comment]
Hi Laura, Without seeing your surface and the contour lines, it is hard for me the evalute the problem. There could be for example problems with your own generated stl surface and the target field ? They should not overlap, otherwise strange behaviour can occur .Is everthing well defined here? Best, Philipp

**Comment by Philipp-MR** [comment]
Well i just read again you error message, and it seems that the parameterization has problems. Make sure to choose the iterate parameterization and not the cylindrical one. It is crucial for that step that your custom mesh is properly defined i.e. regarding normals.
